"""Generate the gallery page of the project wiki.

``docs/maps.md`` is the inventory of the maps. It holds the facts and it must stay
readable in a pull request, so it carries two pictures of a map and no video. The wiki
page carries every tour picture and the link to the tour video of the newest release.

The page is generated. A person must never edit it in the wiki, because the next run
replaces it. ``scripts/publish-tours.sh`` writes it and pushes it.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from fpv_maps.config import MapConfig

TITLE = "Map tours"
PAGE_NAME = "Map-tours.md"


def repo_slug(cwd: Path | None = None) -> str:
    """The ``owner/name`` of the origin remote, for a raw file link."""
    url = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    match = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?$", url)
    if not match:
        raise ValueError(f"cannot read owner/name from the remote {url!r}")
    return match.group(1)


def tour_stills(screenshots: Path, name: str) -> list[Path]:
    """Every tour picture of one map, in shot order."""

    def number(path: Path) -> int:
        parts = path.stem.split("-tour-")
        tail = parts[-1].split("-")[0]
        return int(tail) if tail.isdigit() else 0

    return sorted(screenshots.glob(f"{name}-tour-*.jpg"), key=number)


def ingame_shots(screenshots: Path, name: str) -> list[Path]:
    """Every in-game screenshot of one map, in number order."""
    return sorted(screenshots.glob(f"{name}-ingame-*.jpg"))


def shot_title(path: Path, name: str) -> str:
    """A readable title from a file name, for example "Tartu mill"."""
    tail = path.stem.replace(f"{name}-tour-", "")
    words = tail.split("-", 1)[-1].replace("-", " ")
    return words[:1].upper() + words[1:]


def gallery_markdown(
    maps: list[MapConfig],
    screenshots: Path,
    repo: str,
    branch: str = "main",
) -> str:
    """The whole wiki page as Markdown.

    Every picture is linked from the repository, so the wiki holds no copy. Every video
    is linked from the newest release, because a video is too large for git.
    """
    raw = f"https://raw.githubusercontent.com/{repo}/{branch}/docs/screenshots"
    lines = [
        f"# {TITLE}",
        "",
        "Every map of [the-zone-fpv-maps](https://github.com/" + repo + "), as pictures.",
        "The pictures come from the pipeline, not from the game: `fpv-maps tour` flies a",
        "camera over the built file and renders the frames. The game has no free camera,",
        "so an in-game picture needs a person at the sticks.",
        "",
        "This page is generated by `fpv-maps gallery`. Do not edit it here. Edit the map",
        "configuration in `maps/` and run the command again.",
        "",
        "The data is from Maa- ja Ruumiamet and it needs attribution. See the `NOTICE`",
        "file of the repository.",
        "",
    ]
    for cfg in maps:
        video = f"https://github.com/{repo}/releases/latest/download/{cfg.name}-tour.mp4"
        lines += [
            f"## {cfg.name}",
            "",
            cfg.description,
            "",
            f"- Area: {cfg.area_km2:.0f} km2, bounding box {list(cfg.bbox.as_tuple())} in L-EST97.",
            f"- [Tour video, 1080p]({video}) from the newest release.",
            f"- [Map file and build report](https://github.com/{repo}/releases/latest).",
            "",
        ]
        preview = screenshots / f"{cfg.name}-preview.jpg"
        if preview.exists():
            lines += [f"[![Preview of {cfg.name}]({raw}/{preview.name})]({raw}/{preview.name})", ""]
        for still in tour_stills(screenshots, cfg.name):
            lines += [
                f"**{shot_title(still, cfg.name)}**",
                "",
                f"[![{still.stem}]({raw}/{still.name})]({raw}/{still.name})",
                "",
            ]
        shots = ingame_shots(screenshots, cfg.name)
        if shots:
            lines += ["**In the game**", ""]
            for shot in shots:
                lines += [f"[![{shot.stem}]({raw}/{shot.name})]({raw}/{shot.name})", ""]
    return "\n".join(lines).rstrip() + "\n"


def write_gallery(
    maps: list[MapConfig],
    screenshots: Path,
    out_dir: Path,
    repo: str,
    branch: str = "main",
) -> Path:
    """Write the page into ``out_dir`` and return its path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / PAGE_NAME
    path.write_text(gallery_markdown(maps, screenshots, repo, branch), encoding="utf-8")
    return path
